fix getting a WrongMethodTypeException on resizing mc
java.lang.invoke.WrongMethodTypeException: expected (class_389,int,int)void but found (Object[])void
this happens because it's varargs and not the same args, so it's boxed in an Object[]